### ISSUE TITLE
Tribe member count is showing wrong value

### ISSUE THREAD

**Issue by lucasfloriani** [getZION/react-native#154]
## :page_facing_up: Description

What is going on? Give a brief summary.

## :bookmark_tabs: Details

The screen showing the information of the tribe is showing the incorrect value of members in the tribe

## :checkered_flag: Tasks

- [ ] Fix the issue of showing the incorrect value of members in the tribe

## :checkered_flag: Definition of fixed

- Showing the correct qty of members in the tribe

**Comment by masterial** [comment]
Issue fixed via relay update.
