### ISSUE TITLE
Podcast stops playing after sometime

### ISSUE THREAD

**Issue by lucasfloriani** [getZION/react-native#155]
## :page_facing_up: Description

What is going on? Give a brief summary.

## :bookmark_tabs: Details

After some time of playing the Podcast it stops without pressing the button to stop

## :checkered_flag: Tasks

- [ ] Fix the issue of podcast stopping playing randomly

## :checkered_flag: Definition of fixed

- Podcast only stops playing if the user press the stop button

**Comment by masterial** [comment]
Should be fixed.
