### ISSUE TITLE
Prevent sending more than one invite on the app if email exist.

### ISSUE THREAD

**Issue by mohamedsamara** [getZION/react-native#183]
## :page_facing_up: Description

Show "invite already exist - created" notification message when requesting invites if the email already exist in invite requests.

Shop api returns "exist" flag now to determine if user has requested an invite or not.

**Comment by lucasfloriani** [comment]
@mohamedsamara I tested the API to check the return but it still returning a new record even if I send the same email two times or more, can you check it for us?

![image](https://user-images.githubusercontent.com/36285126/131230984-bd0e44b7-dea0-4f7d-9950-1c56a9b1826d.png)

**Comment by lucasfloriani** [comment]
I changed the connection to use the shop API but the response is not returning the id when the email is not registered in the database, can you give it a look @mohamedsamara ?

**Comment by lucasfloriani** [comment]
Changes on the backend solved the information we needed on the frontend, PR was merged
