### ISSUE TITLE
Support Page Shows Wrong Version

### ISSUE THREAD

**Issue by masterial** [getZION/react-native#211]
Appstore version 1.11.0 (3) 
Page version 1.12.0

Build number is missing

**Comment by antoniel** [comment]
| ![image](https://user-images.githubusercontent.com/17225358/132701370-71fca8c2-0a3b-46c9-a5b0-bc1b46f26a9d.png)  |  ![image](https://user-images.githubusercontent.com/17225358/132701418-51f09cb4-02da-44f7-86ad-d9904705f44f.png) |
|---|---|
