### ISSUE TITLE
Default "Chat" homescreen shows for a split second when opening

### ISSUE THREAD

**Issue by Entryist** [getZION/react-native#247]
![IMG-4848](https://user-images.githubusercontent.com/14167547/133151648-a16057bc-0713-432e-8c8b-c0cbb643a744.PNG)

Should replace this with the Zion logo, centered the same as the animated one is.

Related: the animated logo only shows for a split second-- should probably show a minimum of ~2 seconds so users see the animation.

At minimum for now let's remove the default "Chat" text from the iOS loading screen.

**Comment by Entryist** [comment]
Showing "Zion" instead of "Chat" is a small improvement, but that entire splash screen should be replaced with a proper iOS splash screen. 

It doesn't need to hold up the 1.13 release, but this does need to stay open until the white flash of boring splash screen stops showing on load.

**Comment by antoniel** [comment]
Replace boring text-only using current logo as splash screen using bootSplash
|  ![Kapture 2021-09-15 at 11 52 01](https://user-images.githubusercontent.com/17225358/133457449-dc91b3c6-e1ed-4f6d-9cb0-6884901eae3f.gif) |
|---|

**Comment by Entryist** [comment]
Looks great! Let's just remember we need to repeat this soon for Android.
