### ISSUE TITLE
Reduce vertical space between messages

### ISSUE THREAD

**Issue by Entryist** [getZION/react-native#255]

**Comment by antoniel** [comment]
Reduce margin top from 30px to 16, looks like:
|Before | After |
|----|----|
|![image](https://user-images.githubusercontent.com/17225358/133469245-c11b2d74-02e2-4be7-b6b1-04e206a8bc1d.png)  | ![image](https://user-images.githubusercontent.com/17225358/133469463-e52cf34e-f217-4563-a457-7184920bd887.png)  |
