### ISSUE TITLE
Figure out issue with support tribe. (no-one can send messages)

### ISSUE THREAD

**Issue by lucasfloriani** [getZION/react-native#45]

**Comment by lucasfloriani** [comment]
Is this already fixed @mohamedsamara ?

**Comment by mohamedsamara** [comment]
@lucasfloriani I think this is fixed.

**Comment by lucasfloriani** [comment]
Moving to column QA because it was fixed a long time ago as we talked about (Fix was a change that was made in the fixed id as 1 to a dynamic id from the user)
