### ISSUE TITLE
Reply disable scroll

### ISSUE THREAD

**Issue by lucasfloriani** [getZION/react-native#50]

**Comment by mohamedsamara** [comment]
@lucasfloriani
The improvement: In the chat screen with all the messages showing, if you swipe to reply to a specific message, the chat messages view scrolls up in a non smooth way. It is related with the reply bar showing at the bottom.

I would say this issue will have low priority.

**Comment by lucasfloriani** [comment]
Closing task because this laggy scroll isn't occurring anymore because of the improvements made on the chat
